### PR TITLE
Add ARM compatibility

### PR DESCRIPTION
**Pull request by jmazanec15**
This PR does some refactoring to add ARM compatibility to the library.

First, I added a `PREFETCH` Macro that maps to the correct prefetch function for the architecture used for compilation. For x86 and x64, it will map to `_mm_prefetch`. For aarch64, it will use gcc's `__builtin_prefetch`. For this, I was following a recommendation in [this post](https://stackoverflow.com/questions/16032202/how-to-use-pld-instruction-in-arm). I think it would be possible to embed assembly, but this seems like it may get a little complex. So, for a first version, I just used `__builtin_prefetch`, but can change if you think another implementation may be better. If the architecture is neither x86 nor aarch64, `PREFETCH` will default to a no-op. After making this change, I was able to compile and run `./release/bunit`.

Second, I refactored `similarity_search/include/method/hnsw_distfunc_opt_impl_inline.h`. Instead of having preprocessor directives inside the functions, I created an implementation of *L2Sqr16Ext*, *L2SqrExt*, *ScalarProduct* for *PORTABLE_SSE2*, *PORTABLE_AVX*, *PORTABLE_NEON*, and a default one for architectures without SIMD support.

Third, I added NEON intrinisics to the *PORTABLE_NEON* functions. For this, I referenced the [ARM Intrinsics guide](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics) and [faiss's ARM support](https://github.com/facebookresearch/faiss/blob/569c855ed0eb93f7b6cef3acdcc7cdd209cf7446/faiss/utils/distances_simd.cpp#L547).

Fourth, I changed a few naming conventions in `similarity_search/include/method/hnsw_distfunc_opt_impl_inline.h` in order to improve readibility with SIMD instructions (at least from my own beginner's perspective).

I ran `./release/bunit` on both a [m5.4xlarge instance](https://aws.amazon.com/ec2/instance-types/m5/) for x86 and [m6g.4xlarge](https://aws.amazon.com/ec2/instance-types/m6/) instance for ARM. Both passed.

### CODE REVIEW

**Comment by searchivarius** [comment]
Awesome, I am gonna look into this soon.

**Comment by searchivarius** [comment]
Hi @jmazanec15 many thanks! One thing about PREFETCH though. On Windows, it needs to be _mm_prefetch I think.

**Comment by searchivarius** [comment]
PS: @jmazanec15 we also seem to have the issue with includes under Windows: https://github.com/nmslib/nmslib/issues/399
VCPKG in fact, includes, a patch: https://github.com/microsoft/vcpkg/blob/256d8a497a77f000168fe5a5b7c90a1962fa76ff/ports/nmslib/fix-headers.patch

**Comment by jmazanec15** [comment]
@searchivarius I added a "portable_prefetch" header file, and included <intrin.h> for Microsoft as specified here: https://docs.microsoft.com/en-us/cpp/intrinsics/x86-intrinsics-list?view=msvc-160. I will test on a Windows machine.

In regards to https://github.com/microsoft/vcpkg/blob/256d8a497a77f000168fe5a5b7c90a1962fa76ff/ports/nmslib/fix-headers.patch, I believe this should be solved by the code change. I removed `#include <sys/time.h>` from test_overlap.cc as well.

**Pull request merged**
