### PR TITLE
Automatically deploy to pypi on tag

### PR DESCRIPTION
**Pull request by scottgigante**
This is a work in progress. Things that are yet to be sorted:

* the correct encrypted password should be added to `appveyor.yml` and to the Travis CI repository settings
* appveyor builds should be re-enabled for the repo
* x86 builds are currently throwing an error on appveyor:

<details>

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -I.\nmslib\similarity_search\include -Ic:\python36\Include -IC:\Users\appveyor\AppData\Roaming\Python\Python36\Include -Ic:\python36\Include -IC:\Users\appveyor\AppData\Roaming\Python\Python36\Include -Ic:\python36\lib\site-packages\numpy\core\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /EHsc /Tpnmslib.cc /Fobuild\temp.win32-3.6\Release\nmslib.obj /EHsc /openmp /O2 /DVERSION_INFO=\"1.7.3.6\"
    nmslib.cc
    c:\projects\nmslib\python_bindings\nmslib\similarity_search\include\utils.h(62): error C2371: 'ssize_t': redefinition; different basic types
    c:\python36\include\pyconfig.h(174): note: see declaration of 'ssize_t'
    c:\projects\nmslib\python_bindings\nmslib\similarity_search\include\distcomp.h(247): warning C4244: 'initializing': conversion from 'std::size_t' to 'float', possible loss of data
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
```

</details>

### CODE REVIEW

**Comment by searchivarius** [comment]
Hi @scottgigante I would need help with this. I asked @benfred to review. Just to double check: 
1. This is for Windows only, right?
2. Will this affect branches other than master?
Thank you!

**Comment by scottgigante** [comment]
Thanks @searchivarius . Some notes:

* I have added deployment scripts to both Appveyor and Travis, so wheels would be built for all combinations of Windows, Mac and Linux on Python 2.7, 3.5, 3.6 and 3.7. Currently only x64 Windows due to the unresolved compilation error.
* This won't affect branches other than master, or any untagged commits - the deployment is written such that it will deploy to pypi when a tagged commit is pushed to master.
* The source distribution will also be deployed on tagged commits, and users can install from source with for example `CFLAGS="-march=avx2" pip install --no-binary nmslib`.

Now that I think about this, I'm not sure what arch is native to Travis CI, so we should probably specify `-march=sse2` for the deployed builds in order to make them as universal as possible.

**Comment by scottgigante** [comment]
Just following up on this - @benfred have you had a chance to look at it?

**Comment by scottgigante** [comment]
Sorry for the delay @searchivarius - I've been underwater with work these last few days but more than happy to help. Shall we take this discussion offline?

**Comment by searchivarius** [comment]
@scottgigante no problem. Regarding offline, sure, please send me an e-mail to leo at boytsov dot info whenever you have time. Thank you!

**Pull request merged**
