### PR TITLE
Fix minor documentation problem and regenerate Python documentation.

### PR DESCRIPTION
**Pull request by huonw**
The extra comma resulted in the following old documentation:

image

and the new version is:

image

Almost all of the changes are just autogenerated by sphinx.

The new rendered form is visible at https://huonw.github.io/nmslib/.

### CODE REVIEW

**Comment by searchivarius** [comment]
Thank you @huonw I will review this soon!

**Comment by huonw** [comment]
Hi @searchivarius, any update? Thanks!

**Comment by searchivarius** [comment]
@huonw I really appreciate help! Please, bear with me: I am quite busy and this needs some review. thanks!

**Comment by searchivarius** [comment]
@huonw ohh, BTW, could you resubmit this to the develop branch?

**Comment by huonw** [comment]
I've changed the branch to `develop`. No problem for the wait. :)

**Comment by benfred** [comment]
lgtm =)

**Comment by searchivarius** [comment]
@benfred and @huonw many thanks! could you also remind me how to re-run sphinx to regenerate docs (for future needs)?

**Comment by huonw** [comment]
I believe I ran `make html` in `python_bindings/docs`.

**Pull request merged**
