### PR TITLE
Add support to build aarch64 wheels

### PR DESCRIPTION
**Pull request by janaknat**
Travis-CI allows for the creation of aarch64 wheels.

Build: https://travis-ci.com/github/janaknat/nmslib/builds/205780637

There are 8-9 failures when testing hnsw. Any suggestions on how to fix these? A majority of the failures are due to expected=0.99 and calculated=~0.98.

Tagging @jmazanec15 since he added ARM compatibility.

### CODE REVIEW

**Comment by janaknat** [comment]
Any ideas on when the ARM patches land on master?

**Comment by searchivarius** [comment]
Many thanks. There are few tests that are failing. They fall into two categories:
1. Somewhat narrow ranges for expected parameter values. These are a bit heuristic, so not surprising they may fail on a different compiler and architecture. I will just simply "loosen" the ranges a bit.
2. There are some failures on MAC OS systems. We will have to investigate.

**Comment by searchivarius** [comment]
Hi @janaknat should be in the master soon, we are almost done. Question (also to @jmazanec15): do you have any idea why we have XCODE failures (after my yesterdays commit ARM builds just fine)? 
https://travis-ci.org/github/nmslib/nmslib

**Comment by janaknat** [comment]
@searchivarius Looking at the Travis logs, the XCode failures all show timeouts. Travis-CI times out after 50 minutes. It can also timeout in 10 minutes if there has been no activity, like a print, in that time period.

Also, thank for merging! We're working on gensim aarch64 wheels and one of the dependencies is nmslib. Since the master branch doesn't have the ARM patches, building nmslib as part of gensim wheel build is failing.

**Comment by jmazanec15** [comment]
@searchivarius @janaknat For all of the mac failures in https://travis-ci.org/github/nmslib/nmslib, it looks like they all have these warnings: 
1. https://travis-ci.org/github/nmslib/nmslib/jobs/747326794#L177-L183
2. https://travis-ci.org/github/nmslib/nmslib/jobs/747326794#L430-L432

In those error files, the job is not getting passed the homebrew update phase, so I do not believe there is an issue with the library specifically on those platforms. That being said, I am wondering if these jobs make sense to keep: https://github.com/nmslib/nmslib/blob/master/.travis.yml#L95-L124. Homebrew and Apple don't support that MacOS version and XCode version.

I believe XCode 12 is meant for Big Sur, so maybe it would make sense to update to that. Here is Travis CI's documentation on MacOS/XCode versions: https://docs-staging.travis-ci.com/user/reference/osx/.

What do you guys think?

**Comment by searchivarius** [comment]
Awesome, thank you. I pushed the changes: -old stuff, +12, let's see how it goes.

**Comment by janaknat** [comment]
@searchivarius Have the travis jobs finished?

**Comment by searchivarius** [comment]
@janaknat @jmazanec15 yes, now all seems to be fine: https://travis-ci.org/github/nmslib/nmslib/builds/747475008

**Comment by janaknat** [comment]
@searchivarius Great! Any estimates on when all the ARM stuff will land on master?

**Comment by searchivarius** [comment]
@janaknat I can merge into master right now, but I am not going to release until we run a few more tests, which should be finished within a week.

**Comment by janaknat** [comment]
@searchivarius Any timeline for aarch64 wheels?

**Comment by searchivarius** [comment]
@janaknat this week or so, I am close to finish the test script. Thank you and sorry about the delay.

**Comment by janaknat** [comment]
@searchivarius Howdy. Any updates on the aarch64 wheel?

**Comment by searchivarius** [comment]
@janaknat I am actively working on the benchmarking script. Sorry about the delay, but I want to be more thorough with the current and future releases to prevent possible performance regressions. I thought it would be ready this Monday, but it's still a couple more days to finish.

**Comment by janaknat** [comment]
@searchivarius Thanks for the update!

**Comment by searchivarius** [comment]
@janaknat I think next week is very-very likely, the hardest benchmark part is implemented: https://github.com/nmslib/nmslib/tree/develop/benchmark

**Comment by janaknat** [comment]
@searchivarius That's awesome!

**Comment by searchivarius** [comment]
@janaknat @jmazanec15 I will try build the new release later today.

**Comment by janaknat** [comment]
@searchivarius That's great! Has it been uploaded to PyPI?

**Comment by searchivarius** [comment]
@janaknat yes, just overnight, I had to repeat a process, b/c of the failed test. I think preliminarily it is a success, but we would need to run some benchmarks to be sure.

**Comment by janaknat** [comment]
@searchivarius Are the aarch64 wheels passing the tests?

**Comment by searchivarius** [comment]
@janaknat basic tests: yes, but @jmazanec15 would run some benchmarks soon.

**Comment by janaknat** [comment]
Ok. After the benchmarks will nmslib aarch64 wheels be available on PyPI?

**Comment by searchivarius** [comment]
@janaknat they are already.

**Comment by janaknat** [comment]
@searchivarius I don't see them? https://pypi.org/project/nmslib/#files

**Comment by searchivarius** [comment]
@janaknat sorry for misleading you, I was under impression the build was successful. Something is wrong with the configuration, b/c the build doesn't fail, but deployment somehow doesn't include them:
https://travis-ci.org/github/nmslib/nmslib

**Comment by janaknat** [comment]
Looks like it fails when it can't install eigen3-devel in the deployment step. Is eigen3 a requirement for nmslib?

**Comment by searchivarius** [comment]
@janaknat only if we build NMSLIB with one extra thing that we normally don't include. Could you remove eigen3 from the installation procedure?

**Comment by janaknat** [comment]
Sure. I'll create a PR without eigen3-devel.

**Comment by searchivarius** [comment]
Hi @janaknat it doesn't seem to add aarch64 wheels: https://pypi.org/manage/project/nmslib/release/2.0.9/. You said there was an eigen related error. What's exactly the place (URL) where you found it?

Thank you!

**Comment by janaknat** [comment]
@searchivarius I removed the 2>/dev/null from the deploy stage to see the output.

https://travis-ci.com/github/janaknat/nmslib/jobs/469240144#L6984

I see twine failing waiting for the password.

**Comment by searchivarius** [comment]
Hi @janaknat could you check out ARM binaries that were built recently?

**Comment by janaknat** [comment]
@searchivarius Great! Does a version check work:
```
import nmslib as nms
nms.version
```
Or did you have anything specific in mind?

**Pull request merged**
