### PR TITLE
add python3.8 builds

### PR DESCRIPTION
**Pull request by sjhewitt**

### CODE REVIEW

**Comment by searchivarius** [comment]
@sjhewitt awesome, this is very helpful, many thanks!

**Comment by searchivarius** [comment]
Hi @sjhewitt I am getting a weird build error in Travis, do you have any idea why this might be the case? Thank you!:
https://travis-ci.org/github/nmslib/nmslib/jobs/675530470#L1069

**Comment by sjhewitt** [comment]
I think there's a couple of Ubuntu packages that need installing. I'll open a new PR

**Comment by searchivarius** [comment]
@sjhewitt cool, thank you! I was wondering though what was different with Python 3.8. I look at your changes and they were all consistent with Python 3.x instructions in the travis config.

**Pull request merged**
