### PR TITLE
Add vcpkg installation instructions

### PR DESCRIPTION
**Pull request by NancyLi1013**
`nmslib `is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `nmslib `and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `nmslib`, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/nmslib/portfile.cmake). We try to keep the library maintained as close as possible to the original library.

### CODE REVIEW

**Comment by searchivarius** [comment]
Thank you! Sorry, for the delay. I will try to address this soon.

**Comment by searchivarius** [comment]
Hi @NancyLi1013 
Thanks again, this is quite cool!
What's the repo of the port?

**Comment by searchivarius** [comment]
@NancyLi1013 two more important questions. I may need to move your description to a better place in the documentation. Could you clarify what vcpkg does exactly? Install Windows binaries for Python or something else? NMSLIB also has conda environment package, which I don't maintain. It was also incorporated into Amazon's maintained ElasticSearch distro (I believe it was ElasticSearch and not Lucene). I think I need to mention all these packages somewhere, ideally, from an easy-to-reach place. However, I need to make it clear:
1. These are other people maintaining NMSLIB port. Point to the location of documentation, repo etc
2. Gather these notes in some appropriate documentation page, but not in the place which describes the general build/installation procedure that I take care of.

Thank you!

**Comment by NancyLi1013** [comment]
@searchivarius 
Thanks for looking into this.
If there is another place more suitable to add vcpkg installation instructions, please feel free to move this. I completely agree with your decision.

AS for vcpkg, please refer to this [doc](https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019) to learn more info about vcpkg.

Thanks again for your help.

**Comment by searchivarius** [comment]
Hi @NancyLi1013 this is generic vcpkg doc: you mention that NMSLIB exists as a port. Does it mean there's a separate repo for NMSLIB? Thank you!

**Comment by NancyLi1013** [comment]
@searchivarius 
It's not a separate repo for NMSLIB. It exists in `vcpkg_root_path/ports/nmslib`, you can see this [here](https://github.com/microsoft/vcpkg/tree/master/ports/nmslib).

We just need to clone vcpkg repo and then try to install nmslib and even use it.

**Comment by searchivarius** [comment]
Ohhh @NancyLi1013 I see, very nice. Could you see if this makes sense: 
https://github.com/nmslib/nmslib/blob/master/manual/build.md#building-on-windows

**Comment by NancyLi1013** [comment]
@searchivarius 
Thanks for adding this instructions.

In fact,  `nmslib `can be built on Window, Linux and OSX, via vcpkg.

Since we add the instructions to Windows, it might be better to use the proper command.

```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg integrate install
.\vcpkg install nmslib
```
Since the script `./bootstrap-vcpkg.sh` is for Unix platform. I'm so sorry, it's my fault.

**Comment by searchivarius** [comment]
@NancyLi1013 no worries, so the previous version was to build the system on Linux/MAC?

**Comment by searchivarius** [comment]
@NancyLi1013 one more question: what does exactly vcpkg build? bindings or the whole library?

**Comment by NancyLi1013** [comment]
- For the first question, we can use these command to build on Linux and MacOS:

```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg install nmslib
```
Please refer to this doc https://github.com/microsoft/vcpkg/blob/master/README.md to get more info about this.

- For the second question, mostly, vcpkg will build the whole library.
But for `nmslib`, it seems that only [similarity_search](https://github.com/nmslib/nmslib/tree/master/similarity_search) was built in vcpkg. Please see this file.
https://github.com/microsoft/vcpkg/blob/273b5eddaa2d38b7df285efe915a0ce0ba12b7c5/ports/nmslib/portfile.cmake#L23

**Comment by searchivarius** [comment]
@NancyLi1013 awesome, thank you. So I updated documentation to point out an alternative way to build the library: both Windows & Linux variants. The current version is going to be rather stable, only minor additions & bugfixes. There might be a new major version in the future, but it's a bit uncertain for now.

**Comment by NancyLi1013** [comment]
@searchivarius thanks for your info.
It will be great if there is a new version for `nmslib `to improve it or fix some bugs. We're so glad to hear this. Also we will try to update it as soon as possible if a new version is released.

**Comment by searchivarius** [comment]
Hi @NancyLi1013 please note that this repository is going to be more or less frozen, although I would certainly try fix some annoying bugs that we know how to fix and/or reproduce. Currently, I am preparing a mini-release with two variants of a sparse space and minor bugifxes for empty sparse vectors and making cosine between zero vectors always equal to one. So, if there're easy-to-fix annoying bugs, it would be nice to know (b/c I can include them into this min-release). For the big update, however, it's going to be a new library.

Also, I noticed that you patch headers for proper inclusion of intrinsic-related headers :-) It would be nice if you could create a pull request for these, so this patch could be excluded from vcpkg's further versions.

**Comment by NancyLi1013** [comment]
I will try to do a simple test for `nmslib `in vcpkg. Then I will describe some issues here if there are some bugs that need to fix on your sides.

If possible, I will make a pull request.

**Pull request merged**
