### PR TITLE
bit_jaccard space

### PR DESCRIPTION
**Pull request by gregfriedland**
Hello,
Here's a PR to add a "bit_jaccard" space (discussed in #369) which, much like the "bit_hamming" space, uses bitsets to store the vector of bits. There is a "jaccard_sparse" space which accomplishes the same goal (in that it uses the same distance metric) but it is quite slow and memory intensive because of how it represents the bits (each "on"  bit's index is stored in an int32).

Changes:
* I created an abstract base class SpaceBitVector<dist_t,dist_uint_t> which is templated off the distance metric's type, and a uint of the same size as that type. It's templated because I wanted to try 64 bit types for these, but I couldn't get it to work and got sidetracked so it's currently using 32bits only.
* SpaceBitHamming and SpaceBitJaccard inherit from this ABC
* The BitJaccard distance function uses bit-level ops: "|" and "&"

I ran some tests visualized in the below plots. I expected memory consumption to reduce by a factor of about 16 (since I use 50% sparsity in my test vectors sparse space -> sizeof(int32) * 50% = 16bits) which is not exactly how it panned out but, in any case, it is significant improvement.

Memory
Time

I added some tests, of which the python bit_jaccard, bit_hamming, and sparse_jaccard are currently failing. It seems like it's due to randomness but I'm setting the random seed. Perhaps, there's another random seed that needs to get set?

Greg

### CODE REVIEW

**Comment by searchivarius** [comment]
Hi @gregfriedland thanks a lot: could you submit this to the develop branch?

How do you set the random seed?

**Comment by gregfriedland** [comment]
Sure. Just changed it to go to develop. I'm setting the seed with `np.random.seed(23)`

**Comment by gregfriedland** [comment]
Hi @searchivarius, any thoughts about this PR?

**Comment by searchivarius** [comment]
Hi @gregfriedland something is broken, I will be able to look into this in a couple of weeks. I have deadlines now, sorry.

**Comment by searchivarius** [comment]
Ok thanks again for the pull request, @gregfriedland  I will try to merge it and figure out what's wrong with tests. Likely, it some minor issue.

**Comment by searchivarius** [comment]
Hi @gregfriedland thanks again for your work! I believe there's nothing bad with your code. Unit tests simply could not deal properly with ties in the distance values. The only thing that isn't so good: if one compares two all-zeros vectors, ouch... Well, I don't normally expect this to happen, so it's probably ok for now.

**Comment by gregfriedland** [comment]
Glad it was helpful!

**Pull request merged**
